trailingComma: "es5"
tabWidth: 2
semi: false
singleQuote: true
arrowParens: "avoid"
svelteSelfCloseElements: always
svelteSelfCloseComponents: always
plugins: [prettier-plugin-svelte]
overrides:
  - files: "*.svelte"
    options:
      parser: svelte
